repositories:
  - url: /tmp/test-docs-repo
    name: test-docs
    branch: main
    paths: [docs]
  - url: https://git.home.luguber.info/inful/go-test-project.git
    name: go-test-project
    branch: main
    paths:
      - docs
    auth:
      type: token
      token: "${GIT_ACCESS_TOKEN}"
hugo:
  title: 'Relearn Test Documentation'
  description: 'Testing DocBuilder with Relearn theme using a local repo'
  base_url: 'http://localhost:1316'
  theme: 'relearn'
output:
  directory: '/tmp/relearn-site'
  clean: true
